### ISSUE TITLE
Add home screen widgets

### ISSUE THREAD

**Issue by failsafe42** [jeroen1602/lighthouse_pm#93]
I think having a home screen widget to toggle the base station power would be nice. I was thinking it would look like a power button and could be configured to control a single base station or multiple base stations.

**Comment by jeroen1602** [comment]
This is already added, but not yet released. It's also still a bit buggy, sometimes it doesn't recognize the devices.

See #8 and #86. 

Though these shortcuts don't show the current state of the device. But then again I don't want to have a constant connection with the devices open, as this will cause more problems because only one device can communicate with a lighthouse at a time.
